---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
      - name: install git
        apt: pkg=git state=installed update_cache=true

      - name: install nodejs
        apt: pkg=nodejs state=installed update_cache=true
